# Introduccion a Python

Este es el inicio del curso de **Python**

## Operadores, tipos de variables y cómo asignarlas

### Operadores aritméticos
|Operator |Description            |Syntax|
|:-------:|:---------------------:|:----:|
|+        |Addition               |a + b |
|-        |Subtraction            |a – b |
|*        |Multiplication         |a * b |
|/        |Division (float)       |a / b |
|//       |Floor division         |a // b|
|%        |Modulus (remainder)    |a % b |
|**       |Exponentiation (power) |a ** b|

### Operadores de comparación
|Operator |Description              |Syntax|
|:-------:|:-----------------------:|:----:|
|==       |Equal                    |a == b|
|!=       |Not equal                |a != b|
|>        |Greater than             |a > b |
|<        |Lower than               |a > b |
|>=       |Greater than or equal to |a >= b|
|<=       |Lower than or equal to   |a <= b|

In [1]:
# definición de variables
altura = 1.79 #m
peso = 73.8   #kg

In [2]:
BMI = peso / altura**2
print(altura)
print("el BMI es: ", BMI, "kg/m2")

1.79
el BMI es:  23.032988982865703 kg/m2


In [3]:
# tipos de variables
print(type(BMI))   # número decimal (float)
print(type(5))     # número entero (int)
print(type("BMI")) # un texto (str)
print(type(True))  # tipo boolen (bool)

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [4]:
# el tipo de variable define el comportamiento y las opciones que tengo con esa variable
print(2+3) #suma algebraica
print("ab" + "cd") #concatenar texto

5
abcd


In [5]:
# listas en python
alturas = [1.79, 1.68, 1.71, 1.89]
pesos   = [73.9, 64.1, 78.1, 80.2]

In [6]:
# subconjuntos de listas
print(alturas[0]) #Importante, los índices inician en 0
print(alturas[0:2]) #importante, la selección es intervalo cerrado a la izq y abierto a la derecha: [)
print(alturas[-1]) # los índices negativos, es de atrás para adelante

1.79
[1.79, 1.68]
1.89


In [7]:
# manipulación de listas
alturas[1] = 1.69 #cambiando el segundo elemento de la lista
print(alturas)

[1.79, 1.69, 1.71, 1.89]


In [8]:
# agregar elementos
alturas = alturas + [1.76]
print(alturas)

[1.79, 1.69, 1.71, 1.89, 1.76]


In [9]:
# borrar elemento
del(alturas[-1])
print(alturas)

[1.79, 1.69, 1.71, 1.89]


In [10]:
# ANTENCION: con los nombre y las copias de las listas!!!
alturas_copia = alturas
print(alturas_copia)
alturas_copia[-1] = 1.87
print(alturas_copia)
#peligro!!!
print(alturas) #???

[1.79, 1.69, 1.71, 1.89]
[1.79, 1.69, 1.71, 1.87]
[1.79, 1.69, 1.71, 1.87]


In [11]:
# solución
alturas_copia = list(alturas) # otra forma de hacer una copia: alturas_copia = alturas[:]
print(alturas_copia)
alturas_copia[-1] = 1.89
print(alturas_copia)
# ya no hay peligro
print(alturas)

[1.79, 1.69, 1.71, 1.87]
[1.79, 1.69, 1.71, 1.89]
[1.79, 1.69, 1.71, 1.87]


In [12]:
# funciones sobre las listas
print(max(alturas))
print(min(alturas))

1.87
1.69


In [13]:
# librería Numpy
# %pip install numpy #instalar la librería numpy
import numpy as np #importar la librería/paquete/modulo...

In [14]:
# definición de array en numpy (listas en numpy)
np_alturas = np.array(alturas)
np_pesos   = np.array(pesos)
print(np_alturas)
print(np_pesos)

[1.79 1.69 1.71 1.87]
[73.9 64.1 78.1 80.2]


In [15]:
# mediante listas
BMIs = pesos / alturas**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [16]:
# mediante numpy
BMIs = np_pesos / np_alturas**2
print(BMIs)

[23.064199   22.44319176 26.70907288 22.93459922]


In [17]:
# acceder a elementos de un array en numpy
print(BMIs[1]) # el segundo valor del array
print(BMIs[0:2]) # los dos primeros elementos del array
print(BMIs[-1]) # último

22.443191764994225
[23.064199   22.44319176]
22.934599216448852


In [18]:
# selección basada en criterios
BMIs > 23

array([ True, False,  True, False])

In [19]:
BMIs[BMIs>23]

array([23.064199  , 26.70907288])

In [20]:
# operaciones con Numpy
print(np.mean(BMIs)) # valor medio
print(np.median(BMIs)) # la mediana
print(np.max(BMIs)) # max
print(np.min(BMIs)) # min

23.78776571340132
22.99939910574323
26.709072877124587
22.443191764994225


In [21]:
# doble condicional
BMIs[BMIs>23 and BMIs<25]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
np.logical_and(BMIs>23,BMIs<25)

array([ True, False, False, False])

In [23]:
BMIs[np.logical_and(BMIs>23,BMIs<25)]

array([23.064199])